feat: returnToTitle and executeCommand ws command
OpenWebGAL/WebGAL pull request #593
Opened 2024-11-28 11:36 UTC by ClodLingxi

For issue
[ 模板预览用的游戏，用选项来选择，允许展示任何可能的游戏内界面 #309 ](https://github.com/OpenWebGAL/WebGAL_Terre/issues/309)

2024-11-28 11:42 UTC, MakinoharaShoko commented on packages/webgal/src/Core/util/syncWithEditor/webSocketFunc.ts
> +      resetStage(true);
这里不能重置舞台，也不能清空场景数据，这里的执行指令是为了临时调试脚本服务的。

2024-12-01 13:17 UTC, MakinoharaShoko commented on packages/webgal/src/Core/controller/gamePlay/backToTitle.ts
> +  console.info('showTitle' + webgalStore.getState().GUI.showTitle);
有些控制台输出忘了移除，或者用 logger.debug，这样在生产环境不会输出

2024-12-01 13:19 UTC, MakinoharaShoko commented on packages/webgal/src/Core/util/syncWithEditor/webSocketFunc.ts
> +      webgalStore.dispatch(setVisibility({ component: 'showTitle', visibility: false }));
还有 Menu 界面或者 PanicOverlay 也要关

2024-12-04 14:10 UTC, MakinoharaShoko requested changes

2024-12-04 14:10 UTC, MakinoharaShoko commented on packages/webgal/src/types/debugProtocol.ts
> +  BACK_TO_TITLE,
建议修改为 SET_COMPONENT_VISIBILITY 并用参数来传递需要打开或关闭的组件。

2024-12-05 16:42 UTC, ClodLingxi reviewed
Submit Review

2024-12-14 03:39 UTC, MakinoharaShoko approved these changes

2024-12-14 03:39 UTC, MakinoharaShoko commented on packages/webgal/src/Core/util/syncWithEditor/webSocketFunc.ts
> +      const parse = (commands: string): ({ component: any; visibility: boolean } | undefined)[] => {
为何要用 any

2024-12-14 03:39 UTC, MakinoharaShoko commented on packages/webgal/src/Core/util/syncWithEditor/webSocketFunc.ts
> +      command.forEach((item) => {
1、command = parse(commands) command 和 commands 命名反了吧
2、为什么不用 filter 使代码更简洁

2024-12-14 06:07 UTC, unlimitedcodeG approved these changes

2024-12-20 18:37 UTC, closed without merging

2024-12-20 18:37 UTC, ClodLingxi commented
#610